// <auto-generated />
using System;
using Jobs.RelationalDB.MigrationJob;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Jobs.RelationalDB.MigrationJob.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250315101840_AddRoleSeedData")]
    partial class AddRoleSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Common.Definitions.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSystemRole")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("AppRoles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1d5b3e4-8e5a-4b3c-9ef5-d3e5a3b7c1f8"),
                            CreatedAt = new DateTime(2025, 3, 15, 10, 18, 40, 640, DateTimeKind.Utc).AddTicks(3312),
                            IsDeleted = false,
                            IsSystemRole = true,
                            Name = "Admin",
                            UpdatedAt = new DateTime(2025, 3, 15, 10, 18, 40, 640, DateTimeKind.Utc).AddTicks(3314)
                        },
                        new
                        {
                            Id = new Guid("b3f8a7d1-4e2c-4a3e-8b5a-d3e7b9c5e2f1"),
                            CreatedAt = new DateTime(2025, 3, 15, 10, 18, 40, 640, DateTimeKind.Utc).AddTicks(3318),
                            IsDeleted = false,
                            IsSystemRole = true,
                            Name = "Employer",
                            UpdatedAt = new DateTime(2025, 3, 15, 10, 18, 40, 640, DateTimeKind.Utc).AddTicks(3318)
                        });
                });

            modelBuilder.Entity("Common.Definitions.Domain.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Permission")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermission");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22203303-d215-4fcc-a3b3-31a0fb5100dc"),
                            CreatedAt = new DateTime(2025, 3, 15, 10, 18, 40, 640, DateTimeKind.Utc).AddTicks(3421),
                            IsDeleted = false,
                            Permission = "ManageUsers",
                            RoleId = new Guid("a1d5b3e4-8e5a-4b3c-9ef5-d3e5a3b7c1f8"),
                            UpdatedAt = new DateTime(2025, 3, 15, 10, 18, 40, 640, DateTimeKind.Utc).AddTicks(3421)
                        },
                        new
                        {
                            Id = new Guid("ed48574a-7d01-41fe-844b-2bc0fa4413e7"),
                            CreatedAt = new DateTime(2025, 3, 15, 10, 18, 40, 640, DateTimeKind.Utc).AddTicks(3423),
                            IsDeleted = false,
                            Permission = "ManageRoles",
                            RoleId = new Guid("a1d5b3e4-8e5a-4b3c-9ef5-d3e5a3b7c1f8"),
                            UpdatedAt = new DateTime(2025, 3, 15, 10, 18, 40, 640, DateTimeKind.Utc).AddTicks(3424)
                        },
                        new
                        {
                            Id = new Guid("59516863-e37c-4b72-a6ce-11e464bce34a"),
                            CreatedAt = new DateTime(2025, 3, 15, 10, 18, 40, 640, DateTimeKind.Utc).AddTicks(3426),
                            IsDeleted = false,
                            Permission = "PostJobs",
                            RoleId = new Guid("b3f8a7d1-4e2c-4a3e-8b5a-d3e7b9c5e2f1"),
                            UpdatedAt = new DateTime(2025, 3, 15, 10, 18, 40, 640, DateTimeKind.Utc).AddTicks(3426)
                        },
                        new
                        {
                            Id = new Guid("c89d6edd-5668-4c34-8b44-875c352d4be1"),
                            CreatedAt = new DateTime(2025, 3, 15, 10, 18, 40, 640, DateTimeKind.Utc).AddTicks(3431),
                            IsDeleted = false,
                            Permission = "ViewWorkers",
                            RoleId = new Guid("b3f8a7d1-4e2c-4a3e-8b5a-d3e7b9c5e2f1"),
                            UpdatedAt = new DateTime(2025, 3, 15, 10, 18, 40, 640, DateTimeKind.Utc).AddTicks(3431)
                        });
                });

            modelBuilder.Entity("Common.Definitions.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AuthAccessToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuthProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuthRefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailConfirmationToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Language")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("LastKnownLatitude")
                        .HasColumnType("float");

                    b.Property<double?>("LastKnownLongitude")
                        .HasColumnType("float");

                    b.Property<DateTime?>("LastLocationUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PasswordResetTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordSalt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("Common.Definitions.Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Common.Definitions.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("Common.Definitions.Domain.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Common.Definitions.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("Common.Definitions.Domain.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Common.Definitions.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Common.Definitions.Domain.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
