FROM jenkins/jenkins:lts

USER root

# .NET 8 + Docker CLI kurulumu
RUN apt-get update && \
    apt-get install -y wget apt-transport-https ca-certificates curl gnupg lsb-release docker.io && \
    wget https://packages.microsoft.com/config/debian/11/packages-microsoft-prod.deb -O packages-microsoft-prod.deb && \
    dpkg -i packages-microsoft-prod.deb && \
    apt-get update && \
    apt-get install -y dotnet-sdk-8.0

USER jenkins
