FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY . .
RUN dotnet restore Hirovo.sln
RUN dotnet publish ./BusinessModules/Hirovo/BusinessModules.Hirovo.Api/BusinessModules.Hirovo.Api.csproj -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "BusinessModules.Hirovo.Api.dll"]
