FROM mcr.microsoft.com/dotnet/sdk:8.0

# Gerekli paketler
RUN apt-get update && apt-get install -y \
    git \
    openssh-client

# Git ayarları
RUN git config --global user.name "CI/CD-BOT" && \
    git config --global user.email "bot@hirovo.com" && \
    git config --global push.default matching && \
    git config --global pull.rebase false && \
    git config --global http.sslVerify false && \
    mkdir -p /root/.ssh

# SSH key
COPY _devops/ssh/id_rsa_mobileapp /root/.ssh/id_rsa
RUN chmod 600 /root/.ssh/id_rsa && ssh-keyscan github.com >> /root/.ssh/known_hosts

# ArfBlocks CLI
RUN dotnet tool install --global Arfware.ArfBlocks-cli --version 2.0.0
ENV PATH="${PATH}:/root/.dotnet/tools"

# Proje dosyaları
WORKDIR /maden/backend
COPY . .
COPY BusinessModules ./BusinessModules
COPY BaseModules ./BaseModules
COPY _devops ./_devops

# Geçici klasörler
RUN mkdir -p /maden/backend/_devops/tmp/webapp/common/hirovo-api/src/api/business_modules/hirovo && \
    mkdir -p /maden/backend/_devops/tmp/webapp/common/hirovo-api/src/api/base_modules/iam && \
    mkdir -p /maden/backend/_devops/tmp/webapp/common/hirovo-api/src/errors/locales/modules/common && \
    mkdir -p /maden/backend/_devops/tmp/webapp/common/hirovo-api/src/errors/locales/modules/workers

# ArfBlocks CLI çıktısı üret
RUN arfblocks-cli exec --file /maden/backend/_devops/arfblocks-cli/hirovo.arfblocks-cli.json
RUN arfblocks-cli exec --file /maden/backend/_devops/arfblocks-cli/iam.arfblocks-cli.json

# ErrorCodeExporter
RUN dotnet run --project /maden/backend/Jobs/SpecialPurpose/DevTasks/ErrorCodeExporter/ErrorCodeExporter.csproj || true

# Webapp (maden-frontend) çıktıları kopyalanıyor
RUN mkdir -p /maden/maden-frontend/common && \
    if [ -d "/maden/backend/_devops/tmp/webapp/common" ] && [ "$(ls -A /maden/backend/_devops/tmp/webapp/common)" ]; then \
    cp -r /maden/backend/_devops/tmp/webapp/common/* /maden/maden-frontend/common/; \
    fi

# Mobileapp çıktıları kopyalanıyor
RUN mkdir -p /maden/mobileapp/common && \
    if [ -d "/maden/backend/_devops/tmp/mobileapp/common" ] && [ "$(ls -A /maden/backend/_devops/tmp/mobileapp/common)" ]; then \
    cp -r /maden/backend/_devops/tmp/mobileapp/common/* /maden/mobileapp/common/; \
    fi
