FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Local yapının doğru kopyalandığından emin olmak için önce sadece sln ve ilgili klasörleri kopyala
COPY . .

# Test: SLN dosyasının gerçekten /src içinde olduğunu görmek için
RUN ls -la /src && ls -la /src/BaseModules/IAM/BaseModules.IAM.Api

# Projeyi restore et
RUN dotnet restore /src/Hirovo.sln

# Publish et
RUN dotnet publish /src/BaseModules/IAM/BaseModules.IAM.Api/BaseModules.IAM.Api.csproj -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "BaseModules.IAM.Api.dll"]
