
 @Url= http://localhost:5000
#  @Url=http://3.88.252.189:5000
# @Url= https://api-test.toprak.tkholding.com.tr/koopposbackoffice

  @Jwt =  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIyODM2NzJlNC0xYWU4LTQ1YTctYTkxNC1lMmRlZGQwMjgwYjIiLCJnaXZlbl9uYW1lIjoiam9obmRvMWUxIiwidW5pcXVlX25hbWUiOiJKb2huIERvZSIsInBsYXRmb3JtIjoiMCIsInVzZXJTb3VyY2UiOiIwIiwibmJmIjoxNzQyOTk3OTQ3LCJleHAiOjE3NDM2MDI3NDcsImlhdCI6MTc0Mjk5Nzk0NywiYXVkIjoiaWFtLnRvcHJhay50a2hvbGRpbmcuY29tLnRyIn0.bijr_mwoFDm66rGgGtxoAi03FnVwfQOUCewmpEL7msE"

 
### Create

POST {{Url}}/Jobs/Create  
Authorization: Bearer {{Jwt}}
Accept: application/json
Content-Type: application/json

{
  "title": "Temizlik Personeli",
  "description": "Ofis temizliği için haftada 3 gün çalışacak personel aranıyor.",
  "salary": 550,
  "type": 1,
  "employerId": "283672e4-1ae8-45a7-a914-e2dedd0280b2"
}



### Detail

POST {{Url}}/Jobs/Detail  
Authorization: Bearer {{Jwt}}
Accept: application/json
Content-Type: application/json

{
  "jobId": "5ffb750b-b759-48b3-8b59-7f5017eada23"
}



### All

POST {{Url}}/Jobs/All  
Authorization: Bearer {{Jwt}}
Accept: application/json
Content-Type: application/json

{
  "sorting": null,
  "filters": [],
  "pageRequest": {
    "perPageCount": 20,
    "currentPage": 1,
    "listAll": false
  }
}


### Update

POST {{Url}}/Jobs/Update  
Authorization: Bearer {{Jwt}}
Accept: application/json
Content-Type: application/json

{
  "jobId": "5ffb750b-b759-48b3-8b59-7f5017eada23",
  "title": "Depo Elemanı (Güncellenmiş)",
  "description": "Vardiyalı çalışacak personel aranıyor.",
  "salary": 700,
  "type": 1,
  "status": 1
}


### Delete (soft delete)

POST {{Url}}/Jobs/Delete  
Authorization: Bearer {{Jwt}}
Accept: application/json
Content-Type: application/json

{
  "jobId": "5ffb750b-b759-48b3-8b59-7f5017eada23",
  "isDeleted": true
}


### Pick

POST {{Url}}/Jobs/Pick  
Authorization: Bearer {{Jwt}}
Accept: application/json
Content-Type: application/json

{
  "selectedIds": [],
  "keyword": "temizlik",
  "limit": 10
}




### Create

POST {{Url}}/Jobs/Omer  
Authorization: Bearer {{Jwt}}
Accept: application/json
Content-Type: application/json

{
  "title": "Ömer Ceylan",
  "description": "Ofis temizliği için haftada 3 gün çalışacak personel aranıyor.",
  "salary": 550,
  "type": 1,
  "employerId": "283672e4-1ae8-45a7-a914-e2dedd0280b2"
}

