
 @Url= http://localhost:5000
#  @Url=http://3.88.252.189:5000
# @Url= https://api-test.toprak.tkholding.com.tr/koopposbackoffice

  @Jwt =  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIyODM2NzJlNC0xYWU4LTQ1YTctYTkxNC1lMmRlZGQwMjgwYjIiLCJnaXZlbl9uYW1lIjoiam9obmRvMWUxIiwidW5pcXVlX25hbWUiOiJKb2huIERvZSIsInBsYXRmb3JtIjoiMCIsInVzZXJTb3VyY2UiOiIwIiwibmJmIjoxNzQyOTk3OTQ3LCJleHAiOjE3NDM2MDI3NDcsImlhdCI6MTc0Mjk5Nzk0NywiYXVkIjoiaWFtLnRvcHJhay50a2hvbGRpbmcuY29tLnRyIn0.bijr_mwoFDm66rGgGtxoAi03FnVwfQOUCewmpEL7msE"


### update-profile
POST {{Url}}/Workers/UpdateProfile
Authorization: Bearer {{Jwt}}
Accept: application/json
Content-Type: application/json

{
  "userId": "283672e4-1ae8-45a7-a914-e2dedd0280b2",
  "city": "Ankara",
  "phoneNumber": "05001231231"
}


### detail

POST {{Url}}/Workers/Detail
Authorization: Bearer {{Jwt}}
Accept: application/json
Content-Type: application/json

{
  "userId": "283672e4-1ae8-45a7-a914-e2dedd0280b2"
}


### Pick

POST {{Url}}/Workers/Pick
Authorization: Bearer {{Jwt}}
Accept: application/json
Content-Type: application/json

{
  "selectedIds": [],
  "keyword": "Jo",
  "limit": 5
}
